### ISSUE TITLE
::part(a b c) compiles to ::part(abc)

### ISSUE THREAD

**Issue by bennypowers** [leodido/postcss-clean#39]
Consider an element with id `shadow` whose Shadow Root has this content:

```html
<span part="a">A</span>
<span part="a b">A B</span>
<span part="a b c">A B C</span>
```
And a containing root with these rules
```css
#shadow::part(a) { color: red; }
#shadow::part(a b) { font-weight: bold; }
#shadow::part(a b c) { font-size: large; }
```

## Expected
Before processing, the element will display a red `A`; a red and bold `A B`; and a red, bold, and large `A B C`;
I would expect styles to compile to
```css
#shadow::part(a){color:red;}#shadow::part(a b){font-weight:bold;}#shadow::part(a b c){font-size:large;}
```

## Actual

After processing, the styles were transformed to

```css
#shadow::part(a){color:red;}#shadow::part(ab){font-weight:bold;}#shadow::part(abc){font-size:large;}
```

And the element displays a red `A A B A B C`, but nothing bold or large. 

-----

Thank you for publishing this useful package
